Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2023-07, with the labels that each got.

#13 [fix] updateFirebaseConfig
  src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java
Labels: YuSuHwa🍊

#16 [feat] localSignUp
  build.gradle
  src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/Enum.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumValidator.java
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
  src/main/java/gwasuwonshot/tutice/config/redis/RedisConfig.java
  src/main/java/gwasuwonshot/tutice/config/security/SecurityConfig.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/assembler/UserAssembler.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/LocalSignUpRequestDto.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/LoginResponseDto.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/UserResponseDto.java
  src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
  src/main/java/gwasuwonshot/tutice/user/entity/Role.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#24 [fix] enumValidator
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/Enum.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumModel.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumValidator.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumValue.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Payment.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/LocalSignUpRequestDto.java
  src/main/java/gwasuwonshot/tutice/user/entity/Bank.java
  src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
  src/main/java/gwasuwonshot/tutice/user/entity/Role.java
Labels: fix🐛, SuHwa🍊

#19 [feat] createLesson
  src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/common/dto/ApiResponse.java
  src/main/java/gwasuwonshot/tutice/common/dto/ApiResponseDto.java
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/common/resolver/userId/UserIdResolver.java
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/CreateLessonResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Payment.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidDateException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidTimeException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/advice/LessonControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/RegularScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/advice/ScheduleControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/dto/assembler/AccountAssembler.java
  src/main/java/gwasuwonshot/tutice/user/entity/Account.java
  src/main/java/gwasuwonshot/tutice/user/entity/Bank.java
  src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
  src/main/java/gwasuwonshot/tutice/user/exception/advice/UserControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/InvalidAccessTokenException.java
  src/main/java/gwasuwonshot/tutice/user/exception/userException/NotFoundUserException.java
  src/main/java/gwasuwonshot/tutice/user/repository/AccountRepository.java
Labels: feat🌳, SuHwa🍊

#21 [feat] get lesson by user
  src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonByUserResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/LessonRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SuHwa🍊

#26 [fix] updateEnumValidation to CreateLessonRequestDto
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
Labels: fix🐛, SuHwa🍊

#30 [feat] localLogin
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/LocalLoginRequestDto.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/InvalidPasswordException.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#34 [fix] payment record dbupdate
  src/main/java/gwasuwonshot/tutice/common/entity/AuditingTimeEntity.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/resolver/WebConfig.java
  src/main/java/gwasuwonshot/tutice/common/resolver/userIdx/UserIdx.java
  src/main/java/gwasuwonshot/tutice/common/resolver/userIdx/UserIdxResolver.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/PaymentRecordAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/PaymentRecord.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/PaymentRecordRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/user/entity/Account.java
  src/main/java/gwasuwonshot/tutice/user/entity/NotificationLog.java
Labels: fix🐛, SuHwa🍊

#35 [feat] updateUserDeviceToken
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/resolver/userIdx/UserIdxResolver.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/UpdateUserDeviceTokenRequestDto.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/NullAccessTokenException.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#37 [feat] get lesson detail by parents
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailByParentsResponseLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/NotFoundLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/exception/userException/InvalidRoleException.java
Labels: feat🌳, SuHwa🍊

#39 [feat] getTodayScheduleByParents
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
Labels: feat🌳, SoJung🍋

#43 [fix] date->localDate, time->localTime 타입 변경
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/PaymentRecordAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/PaymentRecord.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/assembler/ScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SoJung🍋

#44 [fix] crateAutoSchedule & update craete lesson
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/EnumValidator.java
  src/main/java/gwasuwonshot/tutice/external/firebase/service/FCMService.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/assembler/ScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
Labels: fix🐛, SuHwa🍊

#45 [feat] getScheduleByUser
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/assembler/ScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/DailySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetScheduleByUserResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByDate.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByUser.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#46 [feat]update lesson parents
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/LessonAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/UpdateLessonParentsRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/AlreadyExistLessonParentsException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidLessonCodeException.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: feat🌳, SuHwa🍊

#50 [feat] create lesson maintenance
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonMaintenanceRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/AlreadyFinishedLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/InvalidLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
Labels: feat🌳, SuHwa🍊

#52 [feat] getTodayScheduleByTeacher
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleByTeacher.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleDetailByTeacher.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#54 [feat] getMissingAttendanceSchedule
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetMissingAttendanceScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/MissingAttendanceSchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/MissingScheduleByDate.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleTimeAndCountInfo.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#56 [feat]get missing maintenance lesson
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetMissingMaintenanceLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetMissingMaintenanceLessonDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/MissingMaintenanceLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/LessonRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
Labels: feat🌳, SuHwa🍊

#60 [feat]get lesson by parents
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/ReturnLongMath.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetMissingMaintenanceLessonDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByParents/GetLessonByParents.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByParents/GetLessonByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonDetail/GetLessonDetailByParentsResponseAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonDetail/GetLessonDetailByParentsResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getMissingMaintenance/GetMissingMaintenanceLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getMissingMaintenance/GetMissingMaintenanceLessonResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getMissingMaintenance/MissingMaintenanceLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/LessonRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SuHwa🍊

#63 [fix] getExpectedScheduleCount
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleTimeAndCountInfo.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodayScheduleDetailByTeacher.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SoJung🍋

#66 [feat]get payment record
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/PaymentRecordController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonMaintenanceRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getPaymentRecordView/GetPaymentRecordViewCycle.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getPaymentRecordView/GetPaymentRecordViewLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getPaymentRecordView/GetPaymentRecordViewResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
Labels: feat🌳, SuHwa🍊

#67 [feat] updateSchedule
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/UpdateScheduleRequestDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/UpdateScheduleRequestSchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/AlreadyUpdateScheduleAttendanceException.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/InvalidScheduleDateException.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#70 [feat] create payment record
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/module/DateAndTimeConvert.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/PaymentRecordController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/PaymentRecordAssembler.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/UpdatePaymentRecordRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/PaymentRecord.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/conflict/AlreadyExistLessonParentsException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/conflict/AlreadyFinishedLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/invalid/InvalidDateException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/invalid/InvalidLessonCodeException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/invalid/InvalidLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/invalid/InvalidPaymentRecordException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/invalid/InvalidTimeException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/notfound/NotFoundLessonException.java
  src/main/java/gwasuwonshot/tutice/lesson/exception/notfound/NotFoundPaymentRecordException.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SuHwa🍊

#77 웨비 테스트를 위한 FCM test 배포
  src/main/java/gwasuwonshot/tutice/external/firebase/FCMTestController.java
  src/main/java/gwasuwonshot/tutice/external/firebase/FCMTestRequestDto.java
Labels: feat🌳, SuHwa🍊

#88 [feat] get lesson by teacher
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacherResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
Labels: feat🌳, SuHwa🍊

#78 [feat] getLatestScheduleByTeacher
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetLatestScheduleByTeacherResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/LatestSchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByTime.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#85 [feat] updateScheduleAttendance
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/ScheduleAttendance.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/UpdateScheduleAttendanceRequestDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/UpdateScheduleAttendanceResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/InvalidAttendanceDateException.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/InvalidAttendanceScheduleException.java
  src/main/java/gwasuwonshot/tutice/schedule/exception/InvalidAttendanceStatusException.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#91 [fix] isMissingAttendanceByLesson 컬럼 추가
  src/main/java/gwasuwonshot/tutice/common/resolver/WebConfig.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByTeacherResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TodaySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SoJung🍋

#98 [feat] request payment record notification
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/user/controller/NotificationController.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/RequestPaymentRecordNotificationResponseDto.java
  src/main/java/gwasuwonshot/tutice/user/entity/NotificationConstant.java
  src/main/java/gwasuwonshot/tutice/user/service/NotificationService.java
Labels: feat🌳, SuHwa🍊

#97 [feat] postMissingAttendance
  src/main/java/gwasuwonshot/tutice/TuticeApplication.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
  src/main/java/gwasuwonshot/tutice/user/entity/NotificationConstant.java
Labels: feat🌳, SoJung🍋

#102 23.07.20 16:22 배포
  src/main/java/gwasuwonshot/tutice/TuticeApplication.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: ci 🎡

#104 getTemporarySchedule
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/GetTemporaryScheduleRequestDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/RegularScheduleByDate.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByDateAndTime.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#105 23.07.21 00:57 배포
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/assembler/RegularScheduleAssembler.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/GetTemporaryScheduleRequestDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/request/RegularScheduleByDate.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/ScheduleByDateAndTime.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: ci 🎡

#106 [fix] getTemporarySchedule
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
Labels: fix🐛, SoJung🍋

#107 23.07.21 16:33 배포
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
Labels: ci 🎡

#109 [fix] 🐛 수업연장 여부 검사시 상태없음이 없음 -> 연장필요ㅗㄹ 변경
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SuHwa🍊

#110 최근스케쥴 뷰에서 isMissing연장 트리거변경
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: ci 🎡

#113 [fix] getPaymentRecordByUser
  src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java
Labels: fix🐛, SuHwa🍊

#114 fix : getPaymentRecordUser 선불후불로 입금내역가져오는 차이로 변경
  src/main/java/gwasuwonshot/tutice/lesson/service/PaymentRecordService.java
Labels: ci 🎡

#115 [fix] getTemporarySchedule res 수정
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporarySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporaryScheduleByTime.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SoJung🍋

#116 23.07.21 22:57 배포
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTemporaryScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporarySchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/TemporaryScheduleByTime.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: ci 🎡

#118 [fix] 선생님 이름 res 수정
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
Labels: fix🐛, SoJung🍋

#120 [hotfix] accesstoken 기간 연장
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
Labels: fix🐛, SuHwa🍊

#122 [hotfix] setTokenPeriod
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
Labels: SuHwa🍊, SoJung🍋, hotfix🚨

#123 hotfix(12시간 acessToken -> 2시간)
  Dockerfile
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
  src/main/java/gwasuwonshot/tutice/schedule/dto/response/GetTodayScheduleByParentsResponseDto.java
Labels: ci 🎡, hotfix🚨
