Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2023-09, with the labels that each got.

#142 [fix] createLesson response에 lessonIdx 추가
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/CreateLessonResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: refactor💡, fix🐛, SoJung🍋

#144 Refactor/#143 update naming
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/PaymentRecordController.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
  src/main/java/gwasuwonshot/tutice/user/controller/NotificationController.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: refactor💡, SuHwa🍊

#145 url 변경
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/PaymentRecordController.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
  src/main/java/gwasuwonshot/tutice/user/controller/NotificationController.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: refactor💡, SuHwa🍊, ci 🎡

#146 Fix/#138 auto create schedule
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
Labels: fix🐛, SuHwa🍊

#148 [fix] get lesosn schedule
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/CreateLessonResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SuHwa🍊

#149 배포 : 미래회차 수업내역, 스케쥴생성 수정
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SuHwa🍊, ci 🎡

#151 [fix] localLogin 이메일 중복 에러 추가
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistEmailException.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: fix🐛, SoJung🍋

#152 23.09.11 22:57 배포 (로컬로그인 이메일 중복 에러 추가)
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistEmailException.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: SuHwa🍊, SoJung🍋, ci 🎡

#154 [feat] checkDuplicationEmail
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/CheckDuplicationEmailRequestDto.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#156 [fix] checkDuplicationEmail 성공 및 실패 메시지 변경
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
Labels: fix🐛, SoJung🍋
