Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2023-10, with the labels that each got.

#160 [fix] create lesson
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValid.java
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValidator.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonMaintenanceRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestRegularSchedule.java
Labels: fix🐛, SuHwa🍊

#162 [feat] getAttendanceExistenceByTeacher
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#167 [feat] get lesson detail
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: feat🌳, SuHwa🍊

#165 23.10.11 21:07 배포
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValid.java
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValidator.java
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/CreateLessonMaintenanceRequestDto.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/GetLessonDetailResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/repository/LessonRepository.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: ci 🎡

#170 fix:🐛 로그아웃 오류 임시 해결
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
Labels: fix🐛

#173 [feat] get lesson regular schedule
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonRegularSchedule/GetLessonRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonRegularSchedule/GetLessonRegularScheduleResponseDto.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: feat🌳, SuHwa🍊

#172 [fix] get lesson by teacher
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacherLatestRegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: fix🐛, SuHwa🍊

#177 [fix] getLessonByTeacher
  src/main/java/gwasuwonshot/tutice/lesson/dto/response/getLessonByTeacher/GetLessonByTeacher.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: fix🐛, SuHwa🍊
