Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2024-04, with the labels that each got.

#199 [feat] validate time range
  src/main/java/gwasuwonshot/tutice/common/advice/ControllerExceptionAdvice.java
  src/main/java/gwasuwonshot/tutice/common/controller/CommonController.java
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/common/resolver/enumValue/Enum.java
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValid.java
  src/main/java/gwasuwonshot/tutice/common/resolver/validator/createLessonValid/CreateLessonValidator.java
Labels: refactor💡, feat🌳, SuHwa🍊

#206 [feat] modifyERD
  src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#216 [feat] modifyERD
  src/main/java/gwasuwonshot/tutice/user/entity/Provider.java
Labels: fix🐛, SoJung🍋

#212 [feat] getNotificationStatus
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/exception/userException/ForbiddenNotificationUserException.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#213 [feat] sendValidationNumber
  build.gradle
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/config/sms/SmsService.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/SendValidationNumberRequest.java
  src/main/java/gwasuwonshot/tutice/user/exception/authException/AlreadyExistPhoneNumberException.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#215 [feat] login, tempSignUp
  src/main/java/gwasuwonshot/tutice/common/dto/ApiResponse.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/LoginRequest.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/LoginResponse.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#217 [feat] signUp
  src/main/java/gwasuwonshot/tutice/config/sms/SmsService.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/SignUpRequest.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#218 [feat] reissueToken
  src/main/java/gwasuwonshot/tutice/common/exception/ErrorStatus.java
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/config/jwt/JwtService.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/ReissueTokenRequest.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/ReissueTokenResponse.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: feat🌳, SoJung🍋

#219 [fix] loginAndTempSignUp
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
Labels: fix🐛, SoJung🍋

#222 [fix] createLesson
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
Labels: fix🐛, SuHwa🍊

#224 [fix] signUp
  src/main/java/gwasuwonshot/tutice/user/entity/User.java
  src/main/java/gwasuwonshot/tutice/user/repository/UserRepository.java
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: fix🐛, SoJung🍋

#225 [fix]getScheduleByLesson
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛, SuHwa🍊

#227 [feat] get canceled schedule by lesson
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SuHwa🍊

#229 [feat] deleteSchedule
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/schedule/controller/ScheduleController.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: feat🌳, SoJung🍋

#231 [feat] getNaverProfileInfo
  src/main/java/gwasuwonshot/tutice/common/exception/SuccessStatus.java
  src/main/java/gwasuwonshot/tutice/external/naver/NaverService.java
  src/main/java/gwasuwonshot/tutice/user/controller/AuthController.java
  src/main/java/gwasuwonshot/tutice/user/dto/request/GetNaverProfileInfoRequest.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/GetNaverProfileInfoResponse.java
Labels: feat🌳, SoJung🍋
