Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2024-05, with the labels that each got.

#233 [fix]createLesson
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestAccount.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: fix🐛, SuHwa🍊

#235 [fix] get account by lesson
  src/main/java/gwasuwonshot/tutice/user/controller/UserController.java
  src/main/java/gwasuwonshot/tutice/user/dto/response/GetAccountByLessonResponse.java
Labels: fix🐛, SuHwa🍊

#238 [fix] ScheduleStatus
  src/main/java/gwasuwonshot/tutice/schedule/entity/ScheduleStatus.java
Labels: fix🐛

#241 [fix] update lesson parents & createLesson
  src/main/java/gwasuwonshot/tutice/lesson/controller/LessonController.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/UpdateLessonParentsRequest.java
  src/main/java/gwasuwonshot/tutice/lesson/dto/request/createLesson/CreateLessonRequestLesson.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/Lesson.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: fix🐛, SuHwa🍊

#243 [fix] sendValidationNumber
  src/main/java/gwasuwonshot/tutice/user/service/UserService.java
Labels: fix🐛, SoJung🍋

#245 [fix] updateLessonParents
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
Labels: fix🐛, SuHwa🍊, SoJung🍋
