Repository Gwasuwon-shot/Tutice_Server, pull requests merged in 2024-03, with the labels that each got.

#192 [refactor] auto create schedule
  src/main/java/gwasuwonshot/tutice/lesson/entity/DayOfWeek.java
  src/main/java/gwasuwonshot/tutice/lesson/entity/RegularSchedule.java
  src/main/java/gwasuwonshot/tutice/lesson/service/LessonService.java
  src/main/java/gwasuwonshot/tutice/schedule/entity/Schedule.java
Labels: refactor💡, SuHwa🍊

#194 [feat] deviceToken nullable 허용
  src/main/java/gwasuwonshot/tutice/user/dto/request/UpdateUserDeviceTokenRequest.java
Labels: feat🌳, SuHwa🍊, SoJung🍋

#197 [fix] getScheduleByUser startTime 기준 오름차순 변경
  src/main/java/gwasuwonshot/tutice/schedule/repository/ScheduleRepository.java
  src/main/java/gwasuwonshot/tutice/schedule/service/ScheduleService.java
Labels: fix🐛
